"""empty message

Revision ID: c0bf6add16f3
Revises: None
Create Date: 2016-10-28 15:42:01.727257

"""

# revision identifiers, used by Alembic.
revision = 'c0bf6add16f3'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('result_all', mysql.JSON(), nullable=True),
    sa.Column('result_no_stop_words', mysql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('result')
    ### end Alembic commands ###
